# Generated by Django 4.1.13 on 2024-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='weight',
            field=models.IntegerField(default=1, help_text='weight in kg'),
            preserve_default=False,
        ),
    ]
