# Generated by Django 4.1.13 on 2024-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0002_trainingsession_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='starting_location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
