# Generated by Django 4.1.13 on 2024-04-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanner', '0003_trainingsession_starting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name for the session', max_length=255, null=True),
        ),
    ]
